### ISSUE TITLE
EventBrite Integration

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/tool-salesforce#3]
See https://docs.google.com/document/d/19x_MnpFw15aGduSITfw-iXulV0LhB2qPbkJA8bD2w3Q/edit#heading=h.77mkx9xdvb7v

**Comment by PeaceGeeksProjects** [comment]
Results of testing on https://test.salesforce.com (append .DevelopPro to your normal user name)

Initial Findings:
1. Events are imported as Campaigns
2. Event Attendees  are added as Campaign members and Contacts
3. Lists are added as Contact Lists (a New object type added by the integration)
4. Orders can be added as opportunities

Requirements clarifications:
EventBrite object and fields mapping: which do we need in SF?

Issue:
Can we create a value that we can filter on or do we need a separate EventBrite User for PeaceTalks

**Comment by PeaceGeeks** [comment]
Issue moved to [PeaceGeeksSociety/salesforce #66](https://github.com/PeaceGeeksSociety/salesforce/issues/66) via [**ZenHub**](https://www.zenhub.com/)
